"""The dedup v2 expectations, asserted with all three flags on.

The fixture is the 200-row stress batch (tests/fixtures/dedup_v2_stress_200.json,
regenerated by tools/build_dedup_v2_fixture.py). The expectation tables live in
tests/dedup_v2_support.py, transcribed from the change request.

Two doubles, two different claims — each test says which one it is making:

* ``SpecOracleLLM`` — a perfect adjudicator. A failure here is the machinery's:
  blocking, slot classification, bucketing or a guard either forbade a merge
  the tables require or forced one they forbid. This is the claim the flags
  exist to make true.
* ``AlwaysSameEntityLLM`` — an adjudicator that says "same entity" to
  everything. It answers the two questions no model-dependent test can:
  did these rows ever reach one block and get compared (MUST_MERGE), and is
  this separation structural rather than a matter of the model's opinion
  (STRUCTURAL_MUST_NOT_MERGE)?

Cluster ids are content hashes of their members, so every assertion is about
set membership, never a literal id.

Neither double says what the live deployment would answer. That is a separate,
reported measurement — see the change report — not something a test can claim.
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

os.environ.setdefault("ENV", "local")
os.environ.setdefault("MOCK_EXTERNAL_CALLS", "true")
os.environ.setdefault("OPENAI_API_KEY", "test-key-for-mocks")

from tests.dedup_v2_support import (  # noqa: E402
    ADDRESS_LESS_MERGE_GROUPS,
    MUST_LINK,
    MUST_LINK_FOR_REVIEW,
    MUST_MERGE,
    MUST_NOT_MERGE,
    STRUCTURAL_MUST_NOT_MERGE,
    V2_FLAGS,
    XFAIL,
    AlwaysSameEntityLLM,
    SpecOracleLLM,
    V1ReplayLLM,
    cluster_of,
    describe,
    fixture_dedup_rows,
    load_fixture,
    run_clustering,
)

#: How much more the model may be consulted with the flags on than without.
#: Delivery-point blocking deliberately widens what is comparable (a house-less
#: row reaches its neighbours, two zips join on city+house), and slot
#: classification moves rows across the Name-2 boundary — both create calls
#: that v1 never made. The budget is here so that widening stays a considered
#: cost rather than an unnoticed one; the exact counts are in the report.
LLM_CALL_BUDGET_RATIO = 3.0


def _run(double_cls, flags_on: bool):
    """One clustering pass at a given flag setting. Module-scoped, so the
    parametrised assertions below all read one run rather than 60."""
    with pytest.MonkeyPatch.context() as monkeypatch:
        for flag in V2_FLAGS:
            monkeypatch.setenv(flag, "true" if flags_on else "false")
        fixture = load_fixture()
        rows = fixture_dedup_rows(fixture)
        llm = double_cls(fixture)
        results, summary = asyncio.run(run_clustering(rows, llm))
    return fixture, results, summary, llm


@pytest.fixture(scope="module")
def oracle_run():
    """Flags on, adjudicated by a model that is always right."""
    return _run(SpecOracleLLM, flags_on=True)


@pytest.fixture(scope="module")
def adversary_run():
    """Flags on, adjudicated by a model that is always wrong in one direction."""
    return _run(AlwaysSameEntityLLM, flags_on=True)


# ---------------------------------------------------------------------------
# MUST_MERGE
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("group", sorted(MUST_MERGE), ids=sorted(MUST_MERGE))
def test_must_merge_shares_one_cluster(group, oracle_run) -> None:
    _fixture, results, _summary, _llm = oracle_run
    row_ids = MUST_MERGE[group]
    clusters = {cluster_of(results, row_id) for row_id in row_ids}
    assert len(clusters) == 1 and None not in clusters, (
        f"{group}: expected one shared Cluster ID across {row_ids}, got "
        f"{sorted(str(c) for c in clusters)}\n{describe(results, row_ids)}"
    )


@pytest.mark.parametrize("group", sorted(MUST_MERGE), ids=sorted(MUST_MERGE))
def test_must_merge_rows_are_comparable_at_all(group, adversary_run) -> None:
    """Blocking and nomination reach these rows, whatever the model thinks.

    Under an adjudicator that merges everything it is asked about, a group that
    still fails to cluster was never asked: its rows landed in different blocks
    or no rule nominated the pair. That is a blocking result and nothing else,
    which is why it is asserted separately from the oracle run above.
    """
    _fixture, results, _summary, _llm = adversary_run
    row_ids = MUST_MERGE[group]
    clusters = {cluster_of(results, row_id) for row_id in row_ids}
    assert len(clusters) == 1 and None not in clusters, (
        f"{group}: rows never became comparable — {sorted(str(c) for c in clusters)}\n"
        f"{describe(results, row_ids)}"
    )


@pytest.mark.parametrize("group", ADDRESS_LESS_MERGE_GROUPS)
def test_an_address_less_merge_still_routes_to_review(group, oracle_run) -> None:
    """The names matched. Nothing said the two records share a door.

    Lee Memorial Health System and United States Gypsum both merge on name
    evidence alone — neither row in either pair carries a usable address. The
    Cluster ID stands because the names are conclusive; the routing says a
    human confirms it, because the delivery point never existed to confirm.
    """
    _fixture, results, _summary, _llm = oracle_run
    row_ids = MUST_MERGE[group]
    routings = {row_id: results[row_id].routing for row_id in row_ids}
    assert set(routings.values()) == {"manual_review"}, (
        f"{group}: an address-less cluster must route to review, got {routings}\n"
        f"{describe(results, row_ids)}"
    )


# ---------------------------------------------------------------------------
# MUST_LINK_FOR_REVIEW
# ---------------------------------------------------------------------------

def link_of(results, row_id):
    """A row's Link ID, or None when it is linked to nothing."""
    return getattr(results.get(row_id), "link_id", None)


@pytest.mark.parametrize("group", sorted(MUST_LINK_FOR_REVIEW), ids=sorted(MUST_LINK_FOR_REVIEW))
def test_must_link_carries_the_finding_in_the_right_column(group, oracle_run) -> None:
    """Which id carries a review link is the whole of what it claims.

    A shared Cluster ID says "these are one record, please confirm". A shared
    Link ID with NO Cluster ID says "these are one organisation and two
    records". Putting a finding in the wrong column either overstates it or
    loses it, so the column is asserted, not just the routing.
    """
    _fixture, results, _summary, _llm = oracle_run
    spec = MUST_LINK_FOR_REVIEW[group]
    row_ids = list(spec.rows)
    clusters = {cluster_of(results, row_id) for row_id in row_ids}
    if spec.shares_cluster:
        assert len(clusters) == 1 and None not in clusters, (
            f"{group}: expected one shared Cluster ID across {row_ids}, got "
            f"{sorted(str(c) for c in clusters)}\n{spec.why}\n"
            f"{describe(results, row_ids)}"
        )
    else:
        links = {link_of(results, row_id) for row_id in row_ids}
        assert len(links) == 1 and None not in links, (
            f"{group}: expected one shared Link ID across {row_ids}, got "
            f"{sorted(str(l) for l in links)}\n{spec.why}\n"
            f"{describe(results, row_ids)}"
        )
        assert len(clusters) == len(row_ids) or clusters == {None}, (
            f"{group}: a link is not a merge — these rows must not share a "
            f"Cluster ID\n{describe(results, row_ids)}"
        )


@pytest.mark.parametrize("group", sorted(MUST_LINK_FOR_REVIEW), ids=sorted(MUST_LINK_FOR_REVIEW))
def test_must_link_routes_every_member_to_manual_review(group, oracle_run) -> None:
    """A link is not a merge: the cluster stands, but a human confirms it.

    The two reasons differ and both must survive to the output — PAVIR's
    delivery point cannot be verified at all, and the two Scripps rows carry
    conflicting ROR ids.
    """
    _fixture, results, _summary, _llm = oracle_run
    row_ids = list(MUST_LINK_FOR_REVIEW[group].rows)
    routings = {row_id: results[row_id].routing for row_id in row_ids if row_id in results}
    assert set(routings.values()) == {"manual_review"}, (
        f"{group}: expected every member to route to manual_review, got {routings}\n"
        f"{describe(results, row_ids)}"
    )


# ---------------------------------------------------------------------------
# MUST_NOT_MERGE
# ---------------------------------------------------------------------------

_NOT_MERGE_IDS = [label for label, _anchors, _forbidden in MUST_NOT_MERGE]


@pytest.mark.parametrize(
    ("label", "anchors", "forbidden"), MUST_NOT_MERGE, ids=_NOT_MERGE_IDS
)
def test_must_not_merge(label, anchors, forbidden, oracle_run) -> None:
    _fixture, results, _summary, _llm = oracle_run
    anchor_clusters = {cluster_of(results, row_id) for row_id in anchors} - {None}
    violations = [
        (row_id, cluster_of(results, row_id))
        for row_id in forbidden
        if cluster_of(results, row_id) is not None
        and cluster_of(results, row_id) in anchor_clusters
    ]
    # Only anchor-against-forbidden. Whether two forbidden rows belong together
    # is a separate question that this table does not answer: the two
    # address-less NASA rows are a real judgement call about "Ames Research
    # Center" against "Intelligent Systems Division / Ames Research Center",
    # and it lives in MODEL_JUDGEMENT. HP against HPE needs no extra rule —
    # one is the anchor and the other is forbidden against it.
    assert not violations, (
        f"{label}: {violations} share a cluster with the anchor group {anchors}\n"
        f"{describe(results, [*anchors, *forbidden])}"
    )


_STRUCTURAL = [
    (label, anchors, forbidden)
    for label, anchors, forbidden in MUST_NOT_MERGE
    if label in STRUCTURAL_MUST_NOT_MERGE
]


@pytest.mark.parametrize(
    ("label", "anchors", "forbidden"), _STRUCTURAL, ids=[t[0] for t in _STRUCTURAL]
)
def test_structural_must_not_merge_survives_a_wrong_model(
    label, anchors, forbidden, adversary_run
) -> None:
    """A different house number is not a judgement call.

    These separations come from the delivery point, so no model verdict is ever
    consulted across them and an adjudicator that merges everything cannot
    join them. If one of these fails, blocking let two delivery points into one
    block — the failure mode B exists to close.
    """
    _fixture, results, _summary, _llm = adversary_run
    anchor_clusters = {cluster_of(results, row_id) for row_id in anchors} - {None}
    violations = [
        (row_id, cluster_of(results, row_id))
        for row_id in forbidden
        if cluster_of(results, row_id) is not None
        and cluster_of(results, row_id) in anchor_clusters
    ]
    assert not violations, (
        f"{label}: blocking let {violations} into the anchor cluster {anchors}\n"
        f"{describe(results, [*anchors, *forbidden])}"
    )


# ---------------------------------------------------------------------------
# MUST_LINK — same organisation, different site
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("group", sorted(MUST_LINK), ids=sorted(MUST_LINK))
def test_must_link_shares_one_link_id(group, oracle_run) -> None:
    """One organisation across several delivery points is ONE Link ID.

    This is the column that carries a same-organisation finding without
    asserting a duplicate, so a missing link is a lost finding — the records
    are related and nothing in the output would say so.
    """
    _fixture, results, _summary, _llm = oracle_run
    spec = MUST_LINK[group]
    links = {row_id: link_of(results, row_id) for row_id in spec.rows}
    assert len(set(links.values())) == 1 and None not in links.values(), (
        f"{group}: expected one shared Link ID.\n{spec.why}\ngot {links}\n"
        f"{describe(results, spec.rows)}"
    )


@pytest.mark.parametrize("group", sorted(MUST_LINK), ids=sorted(MUST_LINK))
def test_must_link_routing(group, oracle_run) -> None:
    """A link states a relationship; it does not by itself demand review.

    Review is for a disagreement — the registry and the model saying different
    things about one pair. Sending every linked pair to a human instead would
    bury the four real questions in this batch under dozens of statements of
    the obvious.
    """
    _fixture, results, _summary, _llm = oracle_run
    spec = MUST_LINK[group]
    if spec.review is None:
        pytest.skip("routing for this group is asserted by its own expectation")
    routings = {row_id: results[row_id].routing for row_id in spec.rows}
    if spec.review:
        assert set(routings.values()) == {"manual_review"}, (
            f"{group}: expected review\n{spec.why}\n{describe(results, spec.rows)}"
        )
    else:
        assert "manual_review" not in routings.values(), (
            f"{group}: a plain link must not route to review — {routings}\n"
            f"{spec.why}\n{describe(results, spec.rows)}"
        )


@pytest.mark.parametrize("group", sorted(MUST_LINK), ids=sorted(MUST_LINK))
def test_must_link_never_clusters_across_sites(group, oracle_run) -> None:
    """A Link is not a Cluster: different sites keep different Cluster IDs."""
    _fixture, results, _summary, _llm = oracle_run
    spec = MUST_LINK[group]
    violations = []
    for i, site in enumerate(spec.sites):
        here = {cluster_of(results, row_id) for row_id in site} - {None}
        for other in spec.sites[i + 1:]:
            there = {cluster_of(results, row_id) for row_id in other} - {None}
            for shared in here & there:
                violations.append((site, other, shared))
    assert not violations, (
        f"{group}: sites share a Cluster ID {violations}\n{spec.why}\n"
        f"{describe(results, spec.rows)}"
    )


# ---------------------------------------------------------------------------
# Known-failing
# ---------------------------------------------------------------------------

@pytest.mark.xfail(
    reason=(
        "Phase 1 overflows 'and Technology' out of Name 1 into Street 1, so the "
        "two NIST rows carry different zip5s (90003 vs 90030) and no comparable "
        "street. Not chased here: the fix is upstream of Phase 2."
    ),
    strict=False,
)
@pytest.mark.parametrize("group", sorted(XFAIL), ids=sorted(XFAIL))
def test_known_failures(group, oracle_run) -> None:
    _fixture, results, _summary, _llm = oracle_run
    row_ids = XFAIL[group]
    clusters = {cluster_of(results, row_id) for row_id in row_ids}
    assert len(clusters) == 1 and None not in clusters, describe(results, row_ids)


# ---------------------------------------------------------------------------
# Cost
# ---------------------------------------------------------------------------

def test_flags_on_does_not_explode_the_call_count() -> None:
    """What the widening costs in model calls, measured rather than assumed.

    Both runs use the same double, so the only difference is what the code
    decided to ask about.
    """
    _f_off, _r_off, off_summary, _l_off = _run(V1ReplayLLM, flags_on=False)
    _f_on, _r_on, on_summary, _l_on = _run(V1ReplayLLM, flags_on=True)
    assert off_summary.llm_calls > 0, "the flags-off run consulted no model at all"
    assert on_summary.llm_calls <= off_summary.llm_calls * LLM_CALL_BUDGET_RATIO, (
        f"flags-on made {on_summary.llm_calls} LLM calls against "
        f"{off_summary.llm_calls} with the flags off — over the "
        f"{LLM_CALL_BUDGET_RATIO}x budget"
    )
